### ISSUE TITLE
Mail database credentials to `travis@justuno.com` on turning the «Provide the developer with the database access» option on

### ISSUE THREAD

**Issue by dmitrii-fediuk** [JustunoCom/m2#35]
[upwork.com/messages/rooms/room_e6b2d182b68bdb5e9bf343521534b1b6/story_80b118ce753eb3a2a14ab6a51cfd1a27](https://www.upwork.com/messages/rooms/room_e6b2d182b68bdb5e9bf343521534b1b6/story_80b118ce753eb3a2a14ab6a51cfd1a27)

**Comment by sbodak** [comment]
It's terrible what you did in this module. It should be blocked by default in the Magento environment and blacklisted forever.
