### ISSUE TITLE
Critical Security Vulnerability (DB Credential Exposure)

### ISSUE THREAD

**Issue by djacques4gorilla** [JustunoCom/m2#39]
The code introduced on March 6th (Justuno\M2\Config\Backend\Debug) can submit production database credentials over a potentially unsecured connection to a static email address that could be compromised (also increasing the likeliness of being compromised as it makes for an interesting target for hackers). This code doesn't belong in a production environment and must be removed from official releases to avoid compromising all Magento applications using this extension that intentionally or accidentally triggers this functionality.

**Comment by dmitrii-fediuk** [comment]
Fixed by https://github.com/justuno-com/m2/issues/41
